// RootLayout.tsx
import React from 'react';
import { Inter } from 'next/font/google'; // Asumiendo que este es el lugar correcto para importar Inter desde next/font/google
import { Metadata } from 'next';

// Definimos la fuente Inter
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Definimos el componente RootLayout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Agregamos la fuente Inter */}
        <style>{`
          ${inter.style}
        `}</style>
        <style>{`
          :root {
            --max-width: 1200px;

            --menu-background: #ffd700; /* Amarillo */
            --menu-text-color: #333;
            --menu-link-hover-color: #ff8c00; /* Naranja */

            --footer-background: #ffd700; /* Amarillo */
            --footer-text-color: #fff;
            --footer-link-hover-color: #ff8c00; /* Naranja */
          }

          /* Estilos para el menú de navegación */
          header {
            background-color: var(--menu-background);
            padding: 20px 0;
          }

          nav {
            text-align: center;
          }

          nav ul {
            list-style: none;
            display: flex;
            justify-content: center;
            margin: 0;
            padding: 0;
          }

          nav li {
            margin: 0 20px;
          }

          nav a {
            color: var(--menu-text-color);
            text-decoration: none;
            font-weight: bold;
            font-size: 18px;
            transition: color 0.3s ease;
          }

          /* Cambios para el enlace "Home" */
          nav a[href="/"] {
            color: yellow; /* Color amarillo */
            padding: 0 20px; /* Ajuste de espacio extra */
          }

          nav a:hover {
            color: var(--menu-link-hover-color);
          }

          /* Estilos para el footer */
          footer {
            background-color: var(--footer-background);
            color: var(--footer-text-color);
            padding: 30px 0;
            text-align: center;
          }

          footer p {
            margin-bottom: 15px;
          }

          footer a {
            color: var(--footer-text-color);
            text-decoration: none;
            font-weight: bold;
            transition: color 0.3s ease;
          }

          footer a:hover {
            color: var(--footer-link-hover-color);
          }
        `}</style>
      </head>
      <body className={inter.className}>
        {/* Header */}
        <header>
          <nav>
            <ul>
              <li><a href="/">Home</a></li>
            </ul>
          </nav>
        </header>

        {/* Contenido de las páginas */}
        {children}

        {/* Footer */}
        <footer>
          <p></p>
        </footer>
      </body>
    </html>
  );
}
